# Generated by Django 4.0 on 2021-12-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_link_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='clicks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
